
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          docker build -t ${{secrets.REGISTRY_USER}}/my-portfolio:${{github.run_number}} .
          docker build -t ${{secrets.REGISTRY_USER}}/my-portfolio .
      - name: Push image
        run: |
          docker login -u ${{secrets.REGISTRY_USER}} -p ${{secrets.REGISTRY_PASS}}
          docker push ${{secrets.REGISTRY_USER}}/my-portfolio:${{github.run_number}}
          docker push ${{secrets.REGISTRY_USER}}/my-portfolio

  scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: ${{secrets.REGISTRY_USER}}/my-portfolio:${{github.run_number}}
          format: table
          exit-code: 1   # fail pipeline if critical/high found
          severity: CRITICAL,HIGH

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Server 
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: 
              docker rm -f resume || true
              docker run -d --name resume -p 8080:5001 ${{secrets.REGISTRY_USER}}/my-portfolio:${{github.run_number}}